# Generated by Django 4.2.2 on 2023-06-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_productoffer_offer_typef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='offer_typef',
        ),
    ]
