# Generated by Django 4.2.2 on 2023-07-03 01:14

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productoffer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='font_awesome',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.category_icon_upload_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.category_banner_upload_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.category_logo_upload_path),
        ),
    ]
