# Generated by Django 4.2.2 on 2023-07-03 05:00

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_category_font_awesome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='filter_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productrelatedimage',
            name='product_image',
            field=models.ImageField(upload_to=inventory.models.product_related_image),
        ),
        migrations.AlterUniqueTogether(
            name='filter',
            unique_together={('filter_group', 'name')},
        ),
    ]
